var character = document.getElementById("character");
var obstacle = document.getElementById("obstacle");
var body = document.getElementsByTagName("body")[0];
var score = 0;
var highScore = 0
var stopScore = false;
var gameOverScreen = document.getElementById("gameOverScreen");
const header = document.querySelector('.eraHeader')
const info = document.querySelector('.eraInfo')

const chars = [
    './images/astronaut.png',
    './images/2.png',
    './images/3.png',
    './images/4.png',
    './images/5.png',
    './images/6.png',
    './images/6.png',
    './images/7.png',
    './images/astronaut.png',
    './images/2.png',
    './images/3.png',
    './images/4.png',
    './images/5.png',
    './images/6.png',
    './images/6.png',
    './images/7.png',
    './images/astronaut.png',
    './images/2.png',
    './images/3.png',
    './images/4.png',
    './images/5.png',
    './images/6.png',
    './images/6.png',
    './images/7.png',
    './images/astronaut.png',
    './images/2.png',
    './images/3.png',
    './images/4.png',
    './images/5.png',
    './images/6.png',
    './images/6.png',
    './images/7.png',
    './images/astronaut.png',
    './images/2.png',
    './images/3.png',
    './images/4.png',
    './images/5.png',
    './images/6.png',
    './images/6.png',
    './images/7.png',
      
    
]

// era info/facts

const eras = [
    "The Stars",
    "The Sunshine",
     "the color of the hair",
    "The attraction",
    "The speed",
    "The darkness",
    "Mesozoic",
    "Oligocene",
    "Quaternary"
]

    const eraInfo = [
        `Stars are diverse celestial objects that vary in size, temperature, and luminosity. They form through the gravitational collapse of gas clouds and undergo nuclear fusion in their cores, emitting light and heat into space. Stars play a crucial role in the structure and dynamics of galaxies, making them the predominant celestial objects in the universe.`,
        `The cosmic microwave background radiation (CMBR) is residual thermal radiation from the early stages of the universe, often referred to as the "afterglow" of the Big Bang. It is isotropic, uniform, and fills all of space, providing strong evidence for the Big Bang theory and supporting the concept of an expanding universe.`,
        `
        The estimated age of the universe is approximately 13.8 billion years. This age is derived from various cosmological observations and measurements, including the study of the cosmic microwave background radiation, the expansion rate of the universe, and the ages of the oldest known objects within it`,
        `The primary forces operating in space and influencing celestial mechanics are gravity and electromagnetism. Gravity governs the motion and interactions of celestial bodies, determining their orbits and shaping the structure of the universe. Electromagnetic forces, such as radiation pressure and magnetic fields, also play a role in celestial dynamics, influencing the behavior of charged particles and interacting with cosmic objects.`,
        `Astronomers detect and study exoplanets using various methods, including the transit method and the radial velocity method. The transit method observes the periodic dimming of a star's brightness as an exoplanet passes in front of it, while the radial velocity method measures the slight wobble of a star caused by the gravitational pull of an orbiting exoplanet. These techniques provide valuable data on exoplanet properties such as size, mass, and orbital characteristics.`,
        `The breakthrough discovery supporting the existence of black holes was the detection of gravitational waves. In 2015, the Laser Interferometer Gravitational-Wave Observatory (LIGO) observed gravitational waves generated by the merger of two black holes. This direct evidence confirmed Albert Einstein's theory of general relativity and provided strong confirmation of the existence of black holes as predicted by the theory.`,
        `The purpose of cosmic rays is not necessarily tied to a specific purpose or function. Cosmic rays are high-energy particles that originate from various astrophysical sources, such as supernovae and active galactic nuclei. They play a crucial role in astrophysics and provide valuable information about the structure of the universe, the acceleration mechanisms of particles, and the magnetic fields in space. Additionally, studying cosmic rays helps us understand the potential impact of high-energy particles on space exploration and human health.`,
        `The predominant theory explaining the origins of the universe is the Big Bang theory. According to this theory, the universe began as a singularity and has been expanding and evolving ever since. The Big Bang theory is supported by various observational evidence, including the cosmic microwave background radiation, the abundance of light elements, and the redshift of galaxies.`,
        `The vacuum of space affects astronauts in multiple ways. Without the atmospheric pressure present on Earth, bodily fluids can boil at lower temperatures, leading to potential damage to tissues and organs. Additionally, exposure to the vacuum can cause decompression sickness, resulting in symptoms similar to the bends experienced by scuba divers resurfacing too quickly. Proper spacesuit and spacecraft systems are essential to protect astronauts from the hazards of the space vacuum.`,
        `The primary objective of space missions is to explore and expand our understanding of the universe, both within our solar system and beyond. Space missions aim to conduct scientific research, advance technological capabilities, study celestial objects, search for signs of life, and potentially establish human presence in space for exploration and colonization purposes.`,
        `Stars are diverse celestial objects that vary in size, temperature, and luminosity. They form through the gravitational collapse of gas clouds and undergo nuclear fusion in their cores, emitting light and heat into space. Stars play a crucial role in the structure and dynamics of galaxies, making them the predominant celestial objects in the universe.`,
        `The cosmic microwave background radiation (CMBR) is residual thermal radiation from the early stages of the universe, often referred to as the "afterglow" of the Big Bang. It is isotropic, uniform, and fills all of space, providing strong evidence for the Big Bang theory and supporting the concept of an expanding universe.`,
        `
        The estimated age of the universe is approximately 13.8 billion years. This age is derived from various cosmological observations and measurements, including the study of the cosmic microwave background radiation, the expansion rate of the universe, and the ages of the oldest known objects within it`,
        `The primary forces operating in space and influencing celestial mechanics are gravity and electromagnetism. Gravity governs the motion and interactions of celestial bodies, determining their orbits and shaping the structure of the universe. Electromagnetic forces, such as radiation pressure and magnetic fields, also play a role in celestial dynamics, influencing the behavior of charged particles and interacting with cosmic objects.`,
        `Astronomers detect and study exoplanets using various methods, including the transit method and the radial velocity method. The transit method observes the periodic dimming of a star's brightness as an exoplanet passes in front of it, while the radial velocity method measures the slight wobble of a star caused by the gravitational pull of an orbiting exoplanet. These techniques provide valuable data on exoplanet properties such as size, mass, and orbital characteristics.`,
        `The breakthrough discovery supporting the existence of black holes was the detection of gravitational waves. In 2015, the Laser Interferometer Gravitational-Wave Observatory (LIGO) observed gravitational waves generated by the merger of two black holes. This direct evidence confirmed Albert Einstein's theory of general relativity and provided strong confirmation of the existence of black holes as predicted by the theory.`,
        `The purpose of cosmic rays is not necessarily tied to a specific purpose or function. Cosmic rays are high-energy particles that originate from various astrophysical sources, such as supernovae and active galactic nuclei. They play a crucial role in astrophysics and provide valuable information about the structure of the universe, the acceleration mechanisms of particles, and the magnetic fields in space. Additionally, studying cosmic rays helps us understand the potential impact of high-energy particles on space exploration and human health.`,
        `The predominant theory explaining the origins of the universe is the Big Bang theory. According to this theory, the universe began as a singularity and has been expanding and evolving ever since. The Big Bang theory is supported by various observational evidence, including the cosmic microwave background radiation, the abundance of light elements, and the redshift of galaxies.`,
        `The vacuum of space affects astronauts in multiple ways. Without the atmospheric pressure present on Earth, bodily fluids can boil at lower temperatures, leading to potential damage to tissues and organs. Additionally, exposure to the vacuum can cause decompression sickness, resulting in symptoms similar to the bends experienced by scuba divers resurfacing too quickly. Proper spacesuit and spacecraft systems are essential to protect astronauts from the hazards of the space vacuum.`,
        `The primary objective of space missions is to explore and expand our understanding of the universe, both within our solar system and beyond. Space missions aim to conduct scientific research, advance technological capabilities, study celestial objects, search for signs of life, and potentially establish human presence in space for exploration and colonization purposes.`,
       
    ]

// checks which key is pressed
function whichKey(event){
    var key = event.keyCode;

    //jumps if key is spacebar, upArrow or 'w'
    if(key == 32 || key == 38 || key == 87){
        jump();
    }

}

//makes the character jump
function jump(){

    if(character.classList.contains("animate")) {return};
    character.classList.add("animate");
    setTimeout(
        () => character.classList.remove("animate"), 800
    );
}

function toggleObstacle(){
    if(obstacle.style.animation != "0s ease 0s 1 normal none running none"){
        obstacle.style.animation = "none"; //stop obstacles
        console.log("stopped");
        console.log(obstacle.style.animation);
    }
    else{
        obstacle.style.animation = "obstacle 1s linear infinite"; //start obstacles
        console.log("started");
    }
}

var gameover = false
//checks if character is touching obstacle
var checkDead = setInterval(() => {
    let characterTop = parseInt(window.getComputedStyle(character).getPropertyValue("top"));
    let obstacleLeft = parseInt(window.getComputedStyle(obstacle).getPropertyValue("left"));

    if(characterTop >= 130 && obstacleLeft <= 20 && obstacleLeft >= -20)
    {
        gameover = true
        toggleObstacle();
        stopScore = true; //stop incrementing score if game is over
        gameOverScreen.style.display = "block"; //display game over screen
        document.getElementById("scoreSpan2").innerHTML = Math.floor(score/100); //display score
        //set new highScore 
        if(score > highScore) highScore = score;
        // score = 0;
        console.log(highScore);
        document.getElementById("highScore").innerHTML = Math.floor(highScore/100);
            
    }
    //if not touching, increment score as obstacle passes below it
    else if(stopScore == false) 
    {
            let displayScore = incrementScore();
            document.getElementById("scoreSpan").innerHTML = displayScore;
    }


    }, 10);
    var i = -1;
    const incre = () => {
        if(!gameover){i++;
            console.log("sdfger")
        header.innerText = eras[i]
        info.innerText = eraInfo[i]
        character.style.backgroundImage = `url(${chars[i]})`
        setTimeout(incre, 3000)
        } else {
            document.querySelector(".gameon").style.display = 'block'
            document.querySelector(".gameover").style.display = 'block'
        }
        }
        // setTimeout(incre, 3000)
        incre()

//restart page on clicking restart button
function restart(){
    document.location.reload();
    console.log('SDFSADGSADF')
    document.querySelector(".gameon").style.display = 'block'
    document.querySelector(".gameover").style.display = 'none'
    toggleObstacle();
    score = 0; 
    gameOverScreen.style.display = "none";
    stopScore = false; 
    level0();
}


function incrementScore() {
    score++;
    let displayScore = Math.floor(score / 100);

    if (displayScore >= 10  ) {
        document.getElementById("transferButton").style.display = "block";
    }

    return displayScore;
}


function level0(){
    character.classList.remove("level0");
}

function level1 (){
    character.classList.add("level0");
}

function darkMode(){
    // body.style.backgroundColor = "black";
    body.classList.add("darkMode");
}

function toggleFullScreen() {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen();
    } else {
      if (document.exitFullscreen) {
        document.exitFullscreen();
      }
    }
  }
  window.addEventListener('keydown', function(e) {
    if (e.keyCode == 32 && e.target == document.body) {
      e.preventDefault();
    }
  });   

document.getElementById("transferButton").addEventListener("click", function() {
    window.location.href = 'https://codecrushe01.on.joget.cloud/jw/web/userview/quiz/quiz/_/quiz_crud?_mode=add';
});
